### ISSUE TITLE
Change License to MIT

### ISSUE THREAD

**Issue by nickhodge** [nickhodge/BoxKite.Twitter#34]
@ghuntley @shiftkey

OK to change License from MS-PL to MIT?

**Comment by shiftkey** [comment]
![](https://user-images.githubusercontent.com/359239/39845024-ad2014d6-5436-11e8-8dc9-00ee9a4acc55.gif)

**Comment by ghuntley** [comment]
Yes. Ship it.

**Comment by ghuntley** [comment]
Shipped - https://github.com/nickhodge/BoxKite.Twitter/blob/master/LICENSE.md
